const TableData=[
    {
        id: "132",
        userID: "234234",
        price: "50k",
        carrier: "viettel",
        status: "not ok",
        report: "false",
        deviceToken: "someToken",
    },
    {
        id: "112",
        userID: "278234",
        price: "100k",
        carrier: "mobiphone",
        status: "not ok",
        report: "false",
        deviceToken: "someothertoken",
    },
    {
        id: "932",
        userID: "278287",
        price: "50k",
        carrier: "viettel",
        status: "not ok",
        report: "true",
        deviceToken: "someMoreToken",
    },
    {
        id: "132",
        userID: "234234",
        price: "50k",
        carrier: "viettel",
        status: "not ok",
        report: "false",
        deviceToken: "someToken",
    },
    {
        id: "132",
        userID: "234234",
        price: "50k",
        carrier: "viettel",
        status: "not ok",
        report: "false",
        deviceToken: "someToken",
    },
    {
        id: "132",
        userID: "234234",
        price: "50k",
        carrier: "viettel",
        status: "not ok",
        report: "false",
        deviceToken: "someToken",
    },
    {
        id: "132",
        userID: "234234",
        price: "50k",
        carrier: "viettel",
        status: "not ok",
        report: "false",
        deviceToken: "someToken",
    },
    {
        id: "132",
        userID: "234234",
        price: "50k",
        carrier: "viettel",
        status: "not ok",
        report: "false",
        deviceToken: "someToken",
    },
    {
        id: "132",
        userID: "234234",
        price: "50k",
        carrier: "viettel",
        status: "not ok",
        report: "false",
        deviceToken: "someToken",
    },
    {
        id: "132",
        userID: "234234",
        price: "50k",
        carrier: "viettel",
        status: "not ok",
        report: "false",
        deviceToken: "someToken",
    },
    {
        id: "132",
        userID: "234234",
        price: "50k",
        carrier: "viettel",
        status: "not ok",
        report: "false",
        deviceToken: "someToken",
    },
    {
        id: "132",
        userID: "234234",
        price: "50k",
        carrier: "viettel",
        status: "not ok",
        report: "false",
        deviceToken: "someToken",
    },
    {
        id: "132",
        userID: "234234",
        price: "50k",
        carrier: "viettel",
        status: "not ok",
        report: "false",
        deviceToken: "someToken",
    },
    {
        id: "132",
        userID: "234234",
        price: "50k",
        carrier: "viettel",
        status: "not ok",
        report: "false",
        deviceToken: "someToken",
    },
    {
        id: "132",
        userID: "234234",
        price: "50k",
        carrier: "viettel",
        status: "not ok",
        report: "false",
        deviceToken: "someToken",
    },
    {
        id: "132",
        userID: "234234",
        price: "50k",
        carrier: "viettel",
        status: "not ok",
        report: "false",
        deviceToken: "someToken",
    },
    {
        id: "132",
        userID: "234234",
        price: "50k",
        carrier: "viettel",
        status: "not ok",
        report: "false",
        deviceToken: "someToken",
    },
    {
        id: "132",
        userID: "234234",
        price: "50k",
        carrier: "viettel",
        status: "not ok",
        report: "false",
        deviceToken: "someToken",
    },
    {
        id: "132",
        userID: "234234",
        price: "50k",
        carrier: "viettel",
        status: "not ok",
        report: "false",
        deviceToken: "someToken",
    },
    {
        id: "132",
        userID: "234234",
        price: "50k",
        carrier: "viettel",
        status: "not ok",
        report: "false",
        deviceToken: "someToken",
    },
    {
        id: "132",
        userID: "234234",
        price: "50k",
        carrier: "viettel",
        status: "not ok",
        report: "false",
        deviceToken: "someToken",
    },
    {
        id: "182",
        userID: "234234",
        price: "50k",
        carrier: "vietnnammobi",
        status: "not ok",
        report: "false",
        deviceToken: "someToken",
    },
]
export {TableData}
